env:
  browser: true
  commonjs: true
  es2021: true
extends: 
  - 'eslint:recommended'
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
plugins:
  - jest
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-unused-vars: off
  no-undef: off
  quotes: off
  semi:
    - error
    - never
